[tool.black]
line-length = 120
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

[tool.check-manifest]
ignore = [".zuul.yaml", ".thoth.yaml", "mypy.ini", ".coafile", ".pre-commit-config.yaml"]
